name: linting

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.25.x"]
        include:
        - go: 1.25.x

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        cache-dependency-path: '**/go.sum'

    - name: Test
      run: go test ./ ./headers ./metric -coverprofile=coverage.txt

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build Examples
      run: go build ./examples/...